name: Daily Build and Release

on:

  schedule:

    - cron: '0 0 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code

      uses: actions/checkout@v2

    - name: Package files

      run: |

        CURRENT_DATE=$(date +'%Y-%m-%d')

        zip -r ${CURRENT_DATE}.zip .

    - name: Upload release

      uses: actions/upload-release-asset@v1

      with:

        asset_path: ${CURRENT_DATE}.zip

        asset_name: ${CURRENT_DATE}.zip

        asset_content_type: application/zip

        tag_name: ${CURRENT_DATE}

        release_name: ${CURRENT_DATE}

      env:

        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
