name: Daily Build and Release
on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Package files
      run: |
        CURRENT_DATE=$(date +'%Y-%m-%d')
        zip -r ${CURRENT_DATE}.zip .

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${CURRENT_DATE}
        release_name: ${CURRENT_DATE}

    - name: Upload release
      uses: actions/upload-release-asset@v1
      with:
        asset_path: ${CURRENT_DATE}.zip
        asset_name: ${CURRENT_DATE}.zip
        asset_content_type: application/zip
        upload_url: ${{ steps.create_release.outputs.upload_url }}
